# Generated by Django 5.1.4 on 2025-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_ecommerse_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerse',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
