# Generated by Django 5.1.4 on 2025-01-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_alter_ecommerse_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Ecommerse',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
