# Generated by Django 5.1.4 on 2025-01-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0007_product_rename_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('membership_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Boook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=20)),
                ('borrowed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_name.member')),
            ],
        ),
    ]
