# Generated by Django 5.1.4 on 2025-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0008_member_boook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('due_date', models.DateField()),
                ('status', models.BooleanField(choices=[(True, 'complete'), (False, 'incomplete')], default=False)),
            ],
        ),
    ]
